cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .gradle/wrapper
  - .gradle/caches

stages:
- build
- "create image"
- "deploy service"

.build_gradle_template: &build_ref
  stage: build
  image: gradle:5.1-jdk
  script:
  - gradle bootJar
  only:
    refs:
    - prod
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 day

.deploy_image_branch_template: &deploy_image_branch_ref
  #PARAM
  #DOCKER_IMAGE_TAG - the docker image tag
  image: docker
  stage: "create image"
  before_script:
  - export CI_PROJECT_PATH_LOWERCASE=`echo $CI_PROJECT_PATH | tr '[:upper:]' '[:lower:]'`
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -f Dockerfile.gitlab-ci -t $CI_REGISTRY/$CI_PROJECT_PATH_LOWERCASE:${DOCKER_IMAGE_TAG} .
  - docker push $CI_REGISTRY/$CI_PROJECT_PATH_LOWERCASE:${DOCKER_IMAGE_TAG}


.deploy_service_template: &deploy_service_ref
  #PARAM
  #ENVIRONMENT_HOST - ip address docker daemon host
  image: docker
  stage: "deploy service"
  cache: {}
  script:
  - export SERVICE_NAME=${CI_COMMIT_REF_NAME}_${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}
  - echo "SERVICE_NAME=$SERVICE_NAME"
  - echo "IMAGE=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker -H ${ENVIRONMENT_HOST} service scale $SERVICE_NAME=0
  - docker -H ${ENVIRONMENT_HOST} rmi -f $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  - docker -H ${ENVIRONMENT_HOST} pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  - docker -H ${ENVIRONMENT_HOST} service update --force $SERVICE_NAME --image $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  - docker -H ${ENVIRONMENT_HOST} service scale $SERVICE_NAME=1


build:
  <<: *build_ref
  only:
    refs:
    - tags
    - test


create image:
  <<: *deploy_image_branch_ref
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME
  only:
  - test

create image tag:
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_TAG
  <<: *deploy_image_branch_ref
  only:
  - tags

deploy test:
  <<: *deploy_service_ref
  variables:
    ENVIRONMENT_HOST: 172.32.1.31
  environment:
    name: prod
    url: https://test-spring.jsql.it/
  only:
    refs:
    - test
